import uuid
from typing import Optional, List
import structlog
from fastapi import APIRouter, Depends, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db_session
from app.authentication.dependencies import require_society_member
from app.authentication.models import UserModel
from app.visitors.schemas import (
    VisitorPassCreate,
    VisitorPassResponse,
)
from app.visitors.services.pass_service import PassService
from app.visitors.routes.common import safe_transaction

router = APIRouter(tags=["Visitor Passes (Residents)"])
logger = structlog.get_logger(__name__)


@router.post(
    "/societies/{society_id}/visitor-passes",
    response_model=VisitorPassResponse,
    status_code=status.HTTP_201_CREATED,
)
async def create_visitor_pass(
    society_id: uuid.UUID,
    payload: VisitorPassCreate,
    db: AsyncSession = Depends(get_db_session),
    current_user: UserModel = Depends(require_society_member),
):
    """
    Resident Endpoint: Pre-approve a visitor with a 6-digit passcode and QR token.
    """
    service = PassService(db)
    async with safe_transaction(db):
        pass_record = await service.create_visitor_pass(
            user_id=current_user.user_id,
            society_id=society_id,
            data=payload,
        )
    return pass_record


@router.get(
    "/societies/{society_id}/visitor-passes",
    response_model=List[VisitorPassResponse],
)
async def list_my_visitor_passes(
    society_id: uuid.UUID,
    status: Optional[str] = None,
    db: AsyncSession = Depends(get_db_session),
    current_user: UserModel = Depends(require_society_member),
):
    """
    Resident Endpoint: List all visitor passes generated by the authenticated user.
    """
    service = PassService(db)
    return await service.list_user_passes(user_id=current_user.user_id, status_filter=status)


@router.get(
    "/societies/{society_id}/visitor-passes/units/{unit_id}",
    response_model=List[VisitorPassResponse],
)
async def list_unit_visitor_passes(
    society_id: uuid.UUID,
    unit_id: uuid.UUID,
    status: Optional[str] = None,
    db: AsyncSession = Depends(get_db_session),
    current_user: UserModel = Depends(require_society_member),
):
    """
    Resident/Admin Endpoint: List visitor passes for a specific unit.
    """
    service = PassService(db)
    return await service.list_unit_passes(unit_id=unit_id, status_filter=status)


@router.get(
    "/societies/{society_id}/visitor-passes/{pass_id}",
    response_model=VisitorPassResponse,
)
async def get_visitor_pass(
    society_id: uuid.UUID,
    pass_id: uuid.UUID,
    db: AsyncSession = Depends(get_db_session),
    current_user: UserModel = Depends(require_society_member),
):
    """
    Get detailed information about a visitor pass.
    """
    service = PassService(db)
    return await service.get_pass(pass_id)


@router.delete(
    "/societies/{society_id}/visitor-passes/{pass_id}",
    response_model=VisitorPassResponse,
)
async def revoke_visitor_pass(
    society_id: uuid.UUID,
    pass_id: uuid.UUID,
    db: AsyncSession = Depends(get_db_session),
    current_user: UserModel = Depends(require_society_member),
):
    """
    Resident Endpoint: Revoke an active visitor pass before check-in.
    """
    service = PassService(db)
    async with safe_transaction(db):
        revoked = await service.revoke_pass(user_id=current_user.user_id, pass_id=pass_id)
    return revoked
